### ISSUE TITLE
[Epic] Bring Superset UI into Superset

### ISSUE THREAD

**Issue by eschutho** [apache-superset/superset-roadmap#128] opened 2021-01-08 00:50 UTC
### Motivation / Problem to Solve
Merge files, keep in central location, etc. @junlincc 

### Proposed Functionality
*** How should the proposed solution work? What are the user expectations? Describe the main use cases or user flows. ***

**Comment by junlincc** [comment] 2021-01-08 15:26
duplicate of [[code_hygiene] Mono repo migration  ](https://github.com/apache-superset/superset-roadmap/issues/122)

Some implementation has already started by Nielsen team

**Closed by junlincc** 2021-01-08 15:26 UTC
