### ISSUE TITLE
[Epic] Replace/convert react-bootstrap to AntD

### ISSUE THREAD

**Issue by eschutho** [apache-superset/superset-roadmap#127] opened 2021-01-08 00:44 UTC
### Motivation / Problem to Solve
We are moving toward AntD for a more modern approach and would like to be able to remove old libraries and have code consistency.

### Proposed Functionality
Remove react-bootstrap library and have all components use AntD instead.

**Comment by junlincc** [comment] 2021-01-08 15:23
Duplicate of [global] Replace remainder of React Bootstrap with AntD

**Closed by junlincc** 2021-01-08 15:23 UTC
